name: Read pull request's inputs
description: Reads inputs from pull request's body as if the action was started by a manual dispatch
inputs:
  workflow-yml-file:
    description: File path to the action.yml file to parse the expected inputs
outputs:
  parsed:
    value: ${{ steps.python-step.outputs.parsed }}

runs:
  using: "composite"
  steps:
    - name: Create branch release
      shell: bash
      run: >
        gh pr view
        $REF
        --json body
        --repo $REPO
        > ${{ github.action_path }}/body.json
      env:
        GH_TOKEN: ${{ github.token }}
        REPO: ${{ github.action_repository }}
        REF: ${{ github.action_ref }}

    - name: Run python
      id: python-step
      shell: bash
      run: |
        echo "parsed=$(python $PYTHON_ARGS)" >> $GITHUB_OUTPUT
      env:
        PYTHON_ARGS: ${{ github.action_path }}/read-inputs.py ${{ inputs.workflow-yml-file }} ${{ github.action_path }}/body.json